name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "ci"
  cancel-in-progress: false


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm test
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        if: always()
        with:
          path: coverage/
      - uses: actions/deploy-pages@v5

